# Generated by Django 4.1 on 2023-05-15 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='icon',
            field=models.ImageField(default=1, upload_to='category/'),
            preserve_default=False,
        ),
    ]
