# Generated by Django 4.1 on 2023-05-21 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0005_remove_recipe_perfil_image_recipe_recipe_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='ingredient_id',
        ),
    ]
