# Generated by Django 4.1 on 2023-05-25 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0006_remove_recipe_ingredient_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='recipe_image',
            field=models.ImageField(blank=True, default='default/índice.png', null=True, upload_to='recipe/'),
        ),
    ]
