# Generated by Django 4.1 on 2023-06-03 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0008_ingredient_recipe'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingredient',
            name='recipe',
        ),
    ]
