# Generated by Django 4.1 on 2023-06-05 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0009_remove_ingredient_recipe'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingredient_recipe',
            name='ingredient',
        ),
        migrations.RemoveField(
            model_name='ingredient_recipe',
            name='recipe',
        ),
        migrations.AddField(
            model_name='recipe',
            name='ingredient',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Ingredient',
        ),
        migrations.DeleteModel(
            name='Ingredient_recipe',
        ),
    ]
